name: Formula CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  ipb-formula:
    runs-on: macos-latest
    steps:
      - name: Check out tap repository
        uses: actions/checkout@v4

      - name: Tap local repository
        run: brew tap smartbartdev/tap "$GITHUB_WORKSPACE"

      - name: Audit formula
        run: brew audit --strict smartbartdev/tap/ipb

      - name: Show formula info
        run: brew info smartbartdev/tap/ipb
