name: Formula CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  ipb-formula:
    runs-on: macos-latest
    steps:
      - name: Check out tap repository
        uses: actions/checkout@v4

      - name: Tap local repository
        run: brew tap smartbartdev/tap "$GITHUB_WORKSPACE"

      - name: Check Ruby syntax
        run: ruby -c Formula/ipb.rb

      - name: Show formula info
        run: brew info smartbartdev/tap/ipb
